In [1]:
import torch
from torch_implementation.mnist_digit_recognizer_neural_net import MNISTDigitRecognizerNeuralNet

# Path to the saved model
saved_model_path = './pytorch_models/mnist_digit_recognizer_neural_net.pth'

# Initialize the model
net = MNISTDigitRecognizerNeuralNet()

# Load trained model weights
if torch.cuda.is_available():
    net.load_state_dict(torch.load(saved_model_path))
else:
    net.load_state_dict(torch.load(saved_model_path, map_location=torch.device('cpu')))

print("Model loaded successfully.")

# Access and print the 3x3 kernels of the first convolutional layer
conv1_kernels = net.conv1.weight.data

print("3x3 Kernels (Weights) of the Conv1 Layer:")
for idx, kernel in enumerate(conv1_kernels):
    print(f"Kernel {idx + 1}:")
    print(kernel.squeeze().cpu().numpy()) 

Model loaded successfully.
3x3 Kernels (Weights) of the Conv1 Layer:
Kernel 1:
[[-0.03431337  0.23040098 -0.32356027]
 [-0.29984933 -0.107909   -0.09893321]
 [-0.3094766   0.05762419  0.16151679]]
Kernel 2:
[[0.14889278 0.30925864 0.06695294]
 [1.0256958  0.72835135 0.9281884 ]
 [1.1492832  0.96711564 0.55681336]]
Kernel 3:
[[-1.4979255  -1.0722408  -1.1007311 ]
 [-0.6175827  -0.31201962 -1.0679379 ]
 [ 1.0477579   1.0510583   0.7730589 ]]
Kernel 4:
[[-0.19065571  0.74855924  1.3533834 ]
 [ 0.12472851  1.5501034   1.3432286 ]
 [ 0.08097316  0.28835735 -0.19931725]]
Kernel 5:
[[ 1.6856706  -0.3631743  -0.78715235]
 [ 0.25925413 -1.0696309  -0.20901743]
 [-0.9097826  -0.0019105   1.3699291 ]]
Kernel 6:
[[ 0.82920474 -0.7190052  -1.5637227 ]
 [ 1.3368105  -0.02833749 -1.4797611 ]
 [ 1.2175187   1.092427    0.26224104]]
Kernel 7:
[[-1.3112082  -1.8706939  -1.5997347 ]
 [ 0.8280369   0.09072771 -0.39141402]
 [ 1.5034438   1.8352776   1.432895  ]]
Kernel 8:
[[-1.3916092  -1.4993192   0.00945

C:\Users\Dan\AppData\Local\Temp\ipykernel_19168\3996700790.py:12: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  net.load_state_dict(torch.load(saved_model_path))
